### ISSUE TITLE
What is our MVP?

### ISSUE THREAD

**Issue by msmichellegar** [foundersandcoders/fac4equality#4]
Just a place to brainstorm features, and eventually prioritise them and decide on our MVP product. Please leave your feedback suggestions below.

**Comment by sohilpandya** [comment]
- Gmail OAuth (get name, email and profile photo)
- Invite Only????

### Landing Page 
- Searching
- Sign up
- Code of Conduct
- FAQ
- How it Works 

### Offering
- Picture of couch
- Intro
- City
- Reviews 
- Option to contact

### Looking
- Profile

### Sign up
- gmail auth, 


### Future
- Reviews (Strech Goal)

**Comment by sohilpandya** [comment]
### User should be able to Sign up
### User should be able to create a profile (if hosting)
### User should be able to select on a city to browse for couches (London + LA)
### User should be able to view the homepage

- [ ] Home page
- [ ] Host page
- [ ] City Page (list of couches, links to host page)

**Comment by sohilpandya** [comment]
### Todo List

- [ ] Setup basic boilerplate (HAPI + HANDLEBARS) 
- [ ] OAuth Google [dwyl-auth-google](https://github.com/dwyl/hapi-auth-google)
- [ ] Landing Page 
    - [ ] Log in / Register
    - [ ] How it Works
    - [ ] Code of Conduct
- [ ] Dashboard
    - [ ] Select City (London/LA)
    - [ ] Sign up to Host
- [ ] Results for a City
    - [ ] list of hosts 
- [ ] Host Signup Page
    - [ ] information
    - [ ] photo url only
